### ISSUE TITLE
CT: Assertion failed: max of one overlapping free coin term when expression is released, seeing 2

### ISSUE THREAD

**Issue by samreid** [phetsims/expression-exchange#145]
This looks like it may have been caused by a change in SimpleDragHandler in https://github.com/phetsims/scenery/issues/206.  One good solution would be to upgrade to use DragListener/PressListener instead of SimpleDragHandler, which is deprecated.

```
expression-exchange : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595719365803/expression-exchange/expression-exchange_en.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1595719365803%22%2C%22timestamp%22%3A1595768109594%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: max of one overlapping free coin term when expression is released, seeing 2
Error: Assertion failed: max of one overlapping free coin term when expression is released, seeing 2
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595719365803/assert/js/assert.js:22:13)
at expressionUserControlledListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595719365803/expression-exchange/js/common/model/ExpressionManipulationModel.js:951:19)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595719365803/axon/js/TinyEmitter.js:69:53)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595719365803/axon/js/Property.js:273:25)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595719365803/axon/js/Property.js:171:14)
at end (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595719365803/expression-exchange/js/common/view/ExpressionOverlayNode.js:158:41)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595719365803/scenery/js/input/SimpleDragHandler.js:238:24
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595719365803/axon/js/Action.js:225:18)
at SimpleDragHandler.endDrag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595719365803/scenery/js/input/SimpleDragHandler.js:354:24)
at Object.up (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1595719365803/scenery/js/input/SimpleDragHandler.js:296:14)
id: Bayes Chrome
Snapshot from 7/25/2020, 5:22:45 PM
```

**Comment by jbphet** [comment]
The CT error disappeared, and I pinged @samreid about it over Slack, but he didn't know why it went away.  We agreed that I could investigate whether it was reasonably easy to make the suggested change and, if not, I could just close the issue.  The change wasn't too hard, so I went forward with it.

Note that I changed from the previous drag handler to the new one without trying to use the automatic boundary testing capabilities of `DragListener`.  That's because the bounding algorithm used is a little unique, and because it was easier to do it this way.

I think this is taken care of, so I'm going to close this issue.  @samreid has a lot of other things going on, but is welcome to review the changes when he sees the notification go by and reopen if he feels it needs any more attention.
