### ISSUE TITLE
CT duplicates are not allowed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/expression-exchange#146]
```
expression-exchange : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596410407643%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught Error: duplicates are not allowed
Error: duplicates are not allowed
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596410407643%7D&fuzz&memoryLimit=1000:89:91394)
at ww.enter (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596410407643%7D&fuzz&memoryLimit=1000:89:631939)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596410407643%7D&fuzz&memoryLimit=1000:89:541105)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596410407643%7D&fuzz&memoryLimit=1000:89:541304)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596410407643%7D&fuzz&memoryLimit=1000:89:540846)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596410407643%7D&fuzz&memoryLimit=1000:89:540463)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596410407643%7D&fuzz&memoryLimit=1000:89:540331)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596410407643%7D&fuzz&memoryLimit=1000:89:539865)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596410407643%7D&fuzz&memoryLimit=1000:89:526175
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596410407643%7D&fuzz&memoryLimit=1000:89:62608)
id: Bayes Chrome
Snapshot from 8/2/2020, 4:47:05 PM

----------------------------------

expression-exchange : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596445395687%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught Error: duplicates are not allowed
Error: duplicates are not allowed
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596445395687%7D&fuzz&memoryLimit=1000:89:91394)
at ww.enter (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596445395687%7D&fuzz&memoryLimit=1000:89:631939)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596445395687%7D&fuzz&memoryLimit=1000:89:541105)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596445395687%7D&fuzz&memoryLimit=1000:89:541304)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596445395687%7D&fuzz&memoryLimit=1000:89:540846)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596445395687%7D&fuzz&memoryLimit=1000:89:540463)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596445395687%7D&fuzz&memoryLimit=1000:89:540331)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596445395687%7D&fuzz&memoryLimit=1000:89:539865)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596445395687%7D&fuzz&memoryLimit=1000:89:526175
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596445395687%7D&fuzz&memoryLimit=1000:89:62608)
id: Bayes Chrome
Snapshot from 8/2/2020, 4:47:05 PM

----------------------------------

expression-exchange : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596455422155%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught Error: duplicates are not allowed
Error: duplicates are not allowed
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596455422155%7D&fuzz&memoryLimit=1000:89:91394)
at ww.enter (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596455422155%7D&fuzz&memoryLimit=1000:89:631939)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596455422155%7D&fuzz&memoryLimit=1000:89:541105)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596455422155%7D&fuzz&memoryLimit=1000:89:541304)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596455422155%7D&fuzz&memoryLimit=1000:89:540846)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596455422155%7D&fuzz&memoryLimit=1000:89:540463)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596455422155%7D&fuzz&memoryLimit=1000:89:540331)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596455422155%7D&fuzz&memoryLimit=1000:89:525274
at i.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596455422155%7D&fuzz&memoryLimit=1000:89:62608)
at t.value (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596455422155%7D&fuzz&memoryLimit=1000:89:534162)
id: Bayes Chrome
Snapshot from 8/2/2020, 4:47:05 PM

----------------------------------

expression-exchange : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/expression-exchange_en.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596409192328%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: duplicates are not allowed
Error: duplicates are not allowed
at ObservableArray.push (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/axon/js/ObservableArray.js:216:13)
at DragListener.enter (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/listeners/PressListener.js:672:23)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1861:25)
at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1893:12)
at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1819:10)
at Input.enterEvents (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1754:14)
at Input.branchChangeEvents (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1724:12)
at Input.moveEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1652:10)
at Input.mouseMoveAction.Action.phetioPlayback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:316:12)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/axon/js/Action.js:225:18)
id: Bayes Chrome
Snapshot from 8/2/2020, 4:47:05 PM

----------------------------------

expression-exchange : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/expression-exchange_en.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596421450000%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: duplicates are not allowed
Error: duplicates are not allowed
at ObservableArray.push (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/axon/js/ObservableArray.js:216:13)
at DragListener.enter (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/listeners/PressListener.js:672:23)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1861:25)
at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1893:12)
at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1819:10)
at Input.enterEvents (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1754:14)
at Input.branchChangeEvents (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1724:12)
at Input.moveEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1652:10)
at Input.mouseMoveAction.Action.phetioPlayback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:316:12)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/axon/js/Action.js:225:18)
id: Bayes Chrome
Snapshot from 8/2/2020, 4:47:05 PM

----------------------------------

expression-exchange : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/expression-exchange_en.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596432527854%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: duplicates are not allowed
Error: duplicates are not allowed
at ObservableArray.push (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/axon/js/ObservableArray.js:216:13)
at DragListener.enter (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/listeners/PressListener.js:672:23)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1861:25)
at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1893:12)
at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1819:10)
at Input.enterEvents (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1754:14)
at Input.branchChangeEvents (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1724:12)
at Input.moveEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1652:10)
at Input.mouseMoveAction.Action.phetioPlayback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:316:12)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/axon/js/Action.js:225:18)
id: Bayes Chrome
Snapshot from 8/2/2020, 4:47:05 PM

----------------------------------

expression-exchange : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/expression-exchange_en.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596445609241%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: duplicates are not allowed
Error: duplicates are not allowed
at ObservableArray.push (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/axon/js/ObservableArray.js:216:13)
at DragListener.enter (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/listeners/PressListener.js:672:23)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1861:25)
at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1893:12)
at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1819:10)
at Input.enterEvents (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1754:14)
at Input.branchChangeEvents (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1724:12)
at Input.moveEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1652:10)
at Input.mouseMoveAction.Action.phetioPlayback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:316:12)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/axon/js/Action.js:225:18)
id: Bayes Chrome
Snapshot from 8/2/2020, 4:47:05 PM

----------------------------------

expression-exchange : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/expression-exchange_en.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596456775086%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: duplicates are not allowed
Error: duplicates are not allowed
at ObservableArray.push (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/axon/js/ObservableArray.js:216:13)
at DragListener.enter (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/listeners/PressListener.js:672:23)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1861:25)
at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1893:12)
at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1819:10)
at Input.enterEvents (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1754:14)
at Input.branchChangeEvents (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1724:12)
at Input.moveEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1652:10)
at Input.mouseMoveAction.Action.phetioPlayback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:316:12)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/axon/js/Action.js:225:18)
id: Bayes Chrome
Snapshot from 8/2/2020, 4:47:05 PM

----------------------------------

expression-exchange : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/expression-exchange/expression-exchange_en.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1596408425822%22%2C%22timestamp%22%3A1596447725994%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: duplicates are not allowed
Error: duplicates are not allowed
at ObservableArray.push (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/axon/js/ObservableArray.js:216:13)
at DragListener.enter (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/listeners/PressListener.js:672:23)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1861:25)
at Input.dispatchToTargets (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1893:12)
at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1819:10)
at Input.enterEvents (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1754:14)
at Input.branchChangeEvents (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1724:12)
at Input.moveEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:1652:10)
at Input.mouseMoveAction.Action.phetioPlayback (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/scenery/js/input/Input.js:316:12)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1596408425822/axon/js/Action.js:225:18)
id: Bayes Chrome
Snapshot from 8/2/2020, 4:47:05 PM
```

**Comment by jbphet** [comment]
@jonathanolson - I recently changed this sim over to using `DragListener` instead of `SimpleDragHandler` at the recommendation of @samreid (see https://github.com/phetsims/expression-exchange/issues/145).  This problem started occurring after that, but it doesn't seem to involve any sim-specific code.  In other words, based on the stack trace that I see in this GitHub issue and when I duplicate it on my machine, the problem seems to be occurring in `DragListener`.  I'm at a bit of a loss to understand why this is happening.  Can you please take a look and see if you have any insights?

**Comment by jonathanolson** [comment]
It's due to the listener getting an "enter", it gets removed, the pointer goes elsewhere, the listener gets re-added and gets another "enter". From https://github.com/phetsims/scenery/issues/1021 we've added a function designed to be used to work around this, called when it is essentially removed from the scene graph, commit included above seems to fix this. @jbphet can you verify, or let me know about any questions?

**Comment by jbphet** [comment]
@jonathanolson - the explanation makes sense, thanks for the fix.  One question: I would be inclined to call `clearOverPointers` when the drag listener is removed and not every time any update to the attachment state occurs.  This seems a little more targeted to me.  I tested this, and it too seemed to fix the problem, but I didn't commit it in case there is a reason you did it the way you did.  Would you be okay with such a change?

**Comment by jonathanolson** [comment]
> Would you be okay with such a change?

Sounds great!

**Comment by jbphet** [comment]
Done, closing.
