### ISSUE TITLE
CT max of one overlapping free coin term when expression is released, seeing 2

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/expression-exchange#150]
```
expression-exchange : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/expression-exchange/expression-exchange_en.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1610062203688%22%2C%22timestamp%22%3A1610102406225%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: max of one overlapping free coin term when expression is released, seeing 2
Error: Assertion failed: max of one overlapping free coin term when expression is released, seeing 2
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/assert/js/assert.js:25:13)
at expressionUserControlledListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/expression-exchange/js/common/model/ExpressionManipulationModel.js:937:19)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/axon/js/TinyEmitter.js:71:18)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/axon/js/Property.js:280:25)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/axon/js/Property.js:178:14)
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/expression-exchange/js/common/view/ExpressionOverlayNode.js:160:43)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/scenery/js/listeners/DragListener.js:338:25
at DragListener.onRelease (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/scenery/js/listeners/PressListener.js:628:17)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/axon/js/Action.js:225:18)
at DragListener.release (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/scenery/js/listeners/PressListener.js:413:25)
id: Bayes Chrome
Snapshot from 1/7/2021, 4:30:03 PM

----------------------------------

expression-exchange : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/expression-exchange/expression-exchange_en.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1610062203688%22%2C%22timestamp%22%3A1610108423787%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: max of one overlapping free coin term when expression is released, seeing 2
Error: Assertion failed: max of one overlapping free coin term when expression is released, seeing 2
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/assert/js/assert.js:25:13)
at expressionUserControlledListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/expression-exchange/js/common/model/ExpressionManipulationModel.js:937:19)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/axon/js/TinyEmitter.js:71:18)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/axon/js/Property.js:280:25)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/axon/js/Property.js:178:14)
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/expression-exchange/js/common/view/ExpressionOverlayNode.js:160:43)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/scenery/js/listeners/DragListener.js:338:25
at DragListener.onRelease (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/scenery/js/listeners/PressListener.js:628:17)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/axon/js/Action.js:225:18)
at DragListener.release (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1610062203688/scenery/js/listeners/PressListener.js:413:25)
id: Bayes Chrome
Snapshot from 1/7/2021, 4:30:03 PM
```

**Comment by jbphet** [comment]
I've updated the drag listeners and the drag forwarding to the latest versions, and CT has been clear for over 24 hours, so I'm going to call this good and close.
