### ISSUE TITLE
CT cannot add the same listener twice

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/expression-exchange#152]
```
expression-exchange : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/expression-exchange/expression-exchange_en.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1620272831901%22%2C%22timestamp%22%3A1620291814081%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: Cannot add the same listener twice
Error: Assertion failed: Cannot add the same listener twice
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/assert/js/assert.js:25:13)
at TinyProperty.addListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/axon/js/TinyEmitter.js:114:15)
at Property.link (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/axon/js/Property.js:375:23)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/expression-exchange/js/common/view/AbstractCoinTermNode.js:124:39
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/axon/js/TinyEmitter.js:86:18)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/axon/js/Property.js:269:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/axon/js/Property.js:184:14)
at Expression.addCoinTerm (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/expression-exchange/js/common/model/Expression.js:408:33)
at addCoinTermAfterAnimation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/expression-exchange/js/common/model/ExpressionManipulationModel.js:1025:29)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1620272831901/axon/js/TinyEmitter.js:86:18)
id: Bayes Chrome
Snapshot from 5/5/2021, 9:47:11 PM
```

**Comment by jbphet** [comment]
I think I have a fix for this, see the commit above.

I worked on #151 at the same time and ran fuzz testing locally for a little over 1/2 hr and saw no problems.  I'll call this fixed, but will watch CT and will reopen if I see it again.  @KatieWoe - you're welcome to do the same.
