### ISSUE TITLE
CT: at least one hint should be active if there is a hovering coin term

### ISSUE THREAD

**Issue by jbphet** [phetsims/expression-exchange#153]
expression-exchange : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1622022158562/expression-exchange/expression-exchange_en.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1622022158562%22%2C%22timestamp%22%3A1622024401998%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: at least one hint should be active if there is a hovering coin term
Error: Assertion failed: at least one hint should be active if there is a hovering coin term
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1622022158562/assert/js/assert.js:25:13)
at expressionUserControlledListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1622022158562/expression-exchange/js/common/model/ExpressionManipulationModel.js:1010:23)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1622022158562/axon/js/TinyEmitter.js:86:18)
at Property._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1622022158562/axon/js/Property.js:270:23)
at Property.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1622022158562/axon/js/Property.js:185:14)
at DragListener.end [as _end] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1622022158562/expression-exchange/js/common/view/ExpressionOverlayNode.js:160:43)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1622022158562/scenery/js/listeners/DragListener.js:335:25
at DragListener.onRelease (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1622022158562/scenery/js/listeners/PressListener.js:680:17)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1622022158562/axon/js/Action.js:227:18)
at DragListener.release (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1622022158562/scenery/js/listeners/PressListener.js:458:25)
id: Bayes Chrome
Snapshot from 5/26/2021, 3:42:38 AM

**Comment by jbphet** [comment]
This hasn't occurred in the last 25 runs of CT, and I'm unable to duplicate it by running the test locally.  I'm going to mark this as "deferred" and will un-defer it if it recurs.  Otherwise I'll close if I don't see it in, say, a month.

**Comment by jbphet** [comment]
We're not seeing it recur in CT, I think we can close it.
