### ISSUE TITLE
CT Cannot read properties of null (reading 'map')

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/expression-exchange#156]
```
expression-exchange : fuzz : built
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652698808733/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1652698808733%22%2C%22timestamp%22%3A1652705919419%7D&fuzz&memoryLimit=1000
Query: fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read properties of null (reading 'map')
TypeError: Cannot read properties of null (reading 'map')
at Ot (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652698808733/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1652698808733%22%2C%22timestamp%22%3A1652705919419%7D&fuzz&memoryLimit=1000:886:102287)
at Rt.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652698808733/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1652698808733%22%2C%22timestamp%22%3A1652705919419%7D&fuzz&memoryLimit=1000:886:102995)
at st.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652698808733/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1652698808733%22%2C%22timestamp%22%3A1652705919419%7D&fuzz&memoryLimit=1000:886:42559)
at ct._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652698808733/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1652698808733%22%2C%22timestamp%22%3A1652705919419%7D&fuzz&memoryLimit=1000:886:84769)
at ct.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652698808733/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1652698808733%22%2C%22timestamp%22%3A1652705919419%7D&fuzz&memoryLimit=1000:886:84145)
at <unknown> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652698808733/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1652698808733%22%2C%22timestamp%22%3A1652705919419%7D&fuzz&memoryLimit=1000:886:1088664)
at st.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652698808733/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1652698808733%22%2C%22timestamp%22%3A1652705919419%7D&fuzz&memoryLimit=1000:886:42435)
at ct._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652698808733/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1652698808733%22%2C%22timestamp%22%3A1652705919419%7D&fuzz&memoryLimit=1000:886:84769)
at ct.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652698808733/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1652698808733%22%2C%22timestamp%22%3A1652705919419%7D&fuzz&memoryLimit=1000:886:84145)
at ct.set value [as value] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652698808733/expression-exchange/build/phet/expression-exchange_en_phet.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22built%22%5D%2C%22snapshotName%22%3A%22snapshot-1652698808733%22%2C%22timestamp%22%3A1652705919419%7D&fuzz&memoryLimit=1000:886:85271)
id: Bayes Chrome
Snapshot from 5/16/2022, 5:00:08 AM

----------------------------------

expression-exchange : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652698808733/expression-exchange/expression-exchange_en.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1652698808733%22%2C%22timestamp%22%3A1652701504953%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Dependencies should be defined, has this Property been disposed?
Error: Assertion failed: Dependencies should be defined, has this Property been disposed?
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652698808733/assert/js/assert.js:28:13)
at assert (DerivedProperty.ts:131:14)
at definedDependencies (DerivedProperty.ts:152:56)
at (TinyEmitter.ts:107:42)
at emit (Property.ts:276:22)
at _notifyListeners (Property.ts:208:13)
at set (ButtonModel.ts:188:24)
at listener (TinyEmitter.ts:93:8)
at emit (Property.ts:276:22)
at _notifyListeners (Property.ts:208:13)
id: Bayes Chrome
Snapshot from 5/16/2022, 5:00:08 AM

----------------------------------

expression-exchange : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652698808733/expression-exchange/expression-exchange_en.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1652698808733%22%2C%22timestamp%22%3A1652716237726%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Dependencies should be defined, has this Property been disposed?
Error: Assertion failed: Dependencies should be defined, has this Property been disposed?
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652698808733/assert/js/assert.js:28:13)
at assert (DerivedProperty.ts:131:14)
at definedDependencies (DerivedProperty.ts:152:56)
at (TinyEmitter.ts:107:42)
at emit (Property.ts:276:22)
at _notifyListeners (Property.ts:208:13)
at set (ButtonModel.ts:188:24)
at listener (TinyEmitter.ts:93:8)
at emit (Property.ts:276:22)
at _notifyListeners (Property.ts:208:13)
id: Bayes Chrome
Snapshot from 5/16/2022, 5:00:08 AM

----------------------------------

expression-exchange : fuzz : unbuilt : assertSlow
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652698808733/expression-exchange/expression-exchange_en.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22assertSlow%22%5D%2C%22snapshotName%22%3A%22snapshot-1652698808733%22%2C%22timestamp%22%3A1652713325662%7D&brand=phet&eall&fuzz&memoryLimit=1000
Query: brand=phet&eall&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Dependencies should be defined, has this Property been disposed?
Error: Assertion failed: Dependencies should be defined, has this Property been disposed?
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652698808733/assert/js/assert.js:28:13)
at assert (DerivedProperty.ts:131:14)
at definedDependencies (DerivedProperty.ts:152:56)
at (TinyEmitter.ts:107:42)
at emit (Property.ts:276:22)
at _notifyListeners (Property.ts:208:13)
at set (ButtonModel.ts:188:24)
at listener (TinyEmitter.ts:93:8)
at emit (Property.ts:276:22)
at _notifyListeners (Property.ts:208:13)
id: Bayes Chrome
Snapshot from 5/16/2022, 5:00:08 AM

----------------------------------

expression-exchange : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652698808733/expression-exchange/expression-exchange_en.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1652698808733%22%2C%22timestamp%22%3A1652701788988%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: Dependencies should be defined, has this Property been disposed?
Error: Assertion failed: Dependencies should be defined, has this Property been disposed?
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652698808733/assert/js/assert.js:28:13)
at assert (DerivedProperty.ts:131:14)
at definedDependencies (DerivedProperty.ts:152:56)
at (TinyEmitter.ts:107:42)
at emit (Property.ts:276:22)
at _notifyListeners (Property.ts:208:13)
at set (ButtonModel.ts:188:24)
at listener (TinyEmitter.ts:93:8)
at emit (Property.ts:276:22)
at _notifyListeners (Property.ts:208:13)
id: Bayes Chrome
Snapshot from 5/16/2022, 5:00:08 AM

----------------------------------

expression-exchange : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652698808733/expression-exchange/expression-exchange_en.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1652698808733%22%2C%22timestamp%22%3A1652715168115%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: Dependencies should be defined, has this Property been disposed?
Error: Assertion failed: Dependencies should be defined, has this Property been disposed?
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652698808733/assert/js/assert.js:28:13)
at assert (DerivedProperty.ts:131:14)
at definedDependencies (DerivedProperty.ts:152:56)
at (TinyEmitter.ts:107:42)
at emit (Property.ts:276:22)
at _notifyListeners (Property.ts:208:13)
at set (ButtonModel.ts:188:24)
at listener (TinyEmitter.ts:93:8)
at emit (Property.ts:276:22)
at _notifyListeners (Property.ts:208:13)
id: Bayes Chrome
Snapshot from 5/16/2022, 5:00:08 AM

----------------------------------

expression-exchange : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652698808733/expression-exchange/expression-exchange_en.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1652698808733%22%2C%22timestamp%22%3A1652702872519%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: Dependencies should be defined, has this Property been disposed?
Error: Assertion failed: Dependencies should be defined, has this Property been disposed?
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652698808733/assert/js/assert.js:28:13)
at assert (DerivedProperty.ts:131:14)
at definedDependencies (DerivedProperty.ts:152:56)
at (TinyEmitter.ts:107:42)
at emit (Property.ts:276:22)
at _notifyListeners (Property.ts:208:13)
at set (ButtonModel.ts:188:24)
at listener (TinyEmitter.ts:93:8)
at emit (Property.ts:276:22)
at _notifyListeners (Property.ts:208:13)
id: Bayes Chrome
Snapshot from 5/16/2022, 5:00:08 AM

----------------------------------

expression-exchange : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652698808733/expression-exchange/expression-exchange_en.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1652698808733%22%2C%22timestamp%22%3A1652710914658%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Dependencies should be defined, has this Property been disposed?
Error: Assertion failed: Dependencies should be defined, has this Property been disposed?
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652698808733/assert/js/assert.js:28:13)
at assert (DerivedProperty.ts:131:14)
at definedDependencies (DerivedProperty.ts:152:56)
at (TinyEmitter.ts:107:42)
at emit (Property.ts:276:22)
at _notifyListeners (Property.ts:208:13)
at set (ButtonModel.ts:188:24)
at listener (TinyEmitter.ts:93:8)
at emit (Property.ts:276:22)
at _notifyListeners (Property.ts:208:13)
id: Bayes Chrome
Snapshot from 5/16/2022, 5:00:08 AM

----------------------------------

expression-exchange : xss-fuzz
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652698808733/expression-exchange/expression-exchange_en.html?continuousTest=%7B%22test%22%3A%5B%22expression-exchange%22%2C%22xss-fuzz%22%5D%2C%22snapshotName%22%3A%22snapshot-1652698808733%22%2C%22timestamp%22%3A1652716203465%7D&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: Dependencies should be defined, has this Property been disposed?
Error: Assertion failed: Dependencies should be defined, has this Property been disposed?
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1652698808733/assert/js/assert.js:28:13)
at assert (DerivedProperty.ts:131:14)
at definedDependencies (DerivedProperty.ts:152:56)
at (TinyEmitter.ts:107:42)
at emit (Property.ts:276:22)
at _notifyListeners (Property.ts:208:13)
at set (ButtonModel.ts:188:24)
at listener (TinyEmitter.ts:93:8)
at emit (Property.ts:276:22)
at _notifyListeners (Property.ts:208:13)
id: Bayes Chrome
Snapshot from 5/16/2022, 5:00:08 AM
```

**Comment by jbphet** [comment]
This seems to have disappeared, see the screenshot below.  Since I haven't been doing any work on this sim, I'm going to assume the problem was something transient in common code and close.

![image](https://user-images.githubusercontent.com/3082831/168859399-5793c489-3867-481f-8fdd-5c2c3dc23f6f.png)
