### ISSUE TITLE
Automated testing error

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/expression-exchange#55]
```
Error: Assertion failed: homeScreenIcon has invalid aspect ratio: 7.493480856233244
    at window.assertions.assertFunction (http://localhost/phet/git/assert/js/assert.js:21:13)
    at validateIconSize (http://localhost/phet/git/joist/js/Screen.js?bust=1486076490109:121:15)
    at EEVariablesScreen.Screen [as constructor] (http://localhost/phet/git/joist/js/Screen.js?bust=1486076490109:77:5)
    at new EEVariablesScreen (http://localhost/phet/git/expression-exchange/js/variables/EEVariablesScreen.js?bust=1486076490109:37:12)
    at http://localhost/phet/git/expression-exchange/js/expression-exchange-main.js?bust=1486076490109:49:9
    at window.phetLaunchSimulation (http://localhost/phet/git/joist/js/SimLauncher.js?bust=1486076490109:50:11)
    at doneLoadingImages (http://localhost/phet/git/joist/js/SimLauncher.js?bust=1486076490109:60:18)
    at Object.launch (http://localhost/phet/git/joist/js/SimLauncher.js?bust=1486076490109:114:9)
    at http://localhost/phet/git/expression-exchange/js/expression-exchange-main.js?bust=1486076490109:43:15
    at Object.execCb (http://localhost/phet/git/sherpa/lib/require-2.1.11.js:1650:25)
```

**Comment by jbphet** [comment]
This looks like it is due to an erroneous commit related to https://github.com/phetsims/scenery/issues/528.

**Comment by jbphet** [comment]
Fixed by fixes to aforementioned scenery issue, closing.
