### ISSUE TITLE
Error: Assertion failed: homeScreenIcon has invalid aspect ratio: ...

### ISSUE THREAD

**Issue by phet-steele** [phetsims/expression-exchange#70]
Run the sim with `?stringTest=xss` to get this error.

```
Uncaught Error: Assertion failed: homeScreenIcon has invalid aspect ratio: 8.728259048257373
Error: Assertion failed: homeScreenIcon has invalid aspect ratio: 8.728259048257373
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1491331930059/assert/js/assert.js:21:13)
    at validateIconSize (https://bayes.colorado.edu/continuous-testing/snapshot-1491331930059/joist/js/Screen.js?bust=1491333288707:119:15)
    at EEVariablesScreen.Screen [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1491331930059/joist/js/Screen.js?bust=1491333288707:75:5)
    at new EEVariablesScreen (https://bayes.colorado.edu/continuous-testing/snapshot-1491331930059/expression-exchange/js/variables/EEVariablesScreen.js?bust=1491333288707:37:12)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1491331930059/expression-exchange/js/expression-exchange-main.js?bust=1491333288707:49:9
    at window.phetLaunchSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1491331930059/joist/js/SimLauncher.js?bust=1491333288707:50:11)
    at doneLoadingImages (https://bayes.colorado.edu/continuous-testing/snapshot-1491331930059/joist/js/SimLauncher.js?bust=1491333288707:60:18)
    at Object.launch (https://bayes.colorado.edu/continuous-testing/snapshot-1491331930059/joist/js/SimLauncher.js?bust=1491333288707:114:9)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1491331930059/expression-exchange/js/expression-exchange-main.js?bust=1491333288707:43:15
    at Object.execCb (https://bayes.colorado.edu/continuous-testing/snapshot-1491331930059/sherpa/lib/require-2.1.11.js:1650:25)
Approximately 4/4/2017, 12:52:10 PM
```

**Comment by jbphet** [comment]
I just tested this on master and it doesn't seem to be happening anymore.  Maybe I fixed it when working on other things, or maybe it was fixed in common code.  Back to @phet-steele to make sure I'm not missing anything.  If the symptom is gone, he can close.

**Comment by phet-steele** [comment]
Might have been fixed after the switch to RichText in https://github.com/phetsims/expression-exchange/commit/fab6d8497b09ddbb7a2962649b8794e1c038bf0e? I don't know, but this error no longer appears.
